# Generated by Django 5.0.6 on 2024-12-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0002_alter_teacher_teaching_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='availability',
            new_name='status',
        ),
    ]
