# Generated by Django 5.0.6 on 2024-12-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0003_rename_availability_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_experience',
        ),
    ]
