# Generated by Django 5.0.6 on 2024-12-25 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0004_remove_teacher_teaching_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='background_check',
        ),
        migrations.AddField(
            model_name='verification',
            name='id_card',
            field=models.FileField(default='-', upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
