# Generated by Django 5.0.6 on 2024-12-25 20:55

import django.core.validators
import manage_tutorlinc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0005_remove_verification_background_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='town',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/', validators=[manage_tutorlinc.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_card',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.validators.validate_file_size]),
        ),
    ]
