# Generated by Django 5.0.6 on 2024-12-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0006_rename_city_address_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_tutorlinc.teacher'),
        ),
    ]
