# Generated by Django 5.0.6 on 2025-01-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0010_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_tutorlinc.teacher'),
        ),
    ]
