# Generated by Django 5.0.6 on 2025-01-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0011_alter_availability_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='availability_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
