# Generated by Django 5.0.6 on 2025-01-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0012_teacher_availability_status_delete_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_tutorlinc.teacher'),
        ),
    ]
