# Generated by Django 5.0.6 on 2025-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0014_remove_verification_id_alter_verification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
    ]
