# Generated by Django 5.0.6 on 2025-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0015_inquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
