# Generated by Django 5.0.6 on 2025-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0016_inquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
