# Generated by Django 5.0.6 on 2025-03-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0017_alter_comment_commenter_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
