# Generated by Django 5.0.6 on 2025-03-17 11:35

import cloudinary.models
import django.core.validators
import manage_tutorlinc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0018_alter_address_region_alter_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_card',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.models.validate_file_size]),
        ),
    ]
