# Generated by Django 5.0.6 on 2025-03-18 17:52

import manage_tutorlinc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0019_alter_teacher_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/', validators=[manage_tutorlinc.validators.validate_file_size]),
        ),
    ]
