# Generated by Django 5.0.6 on 2025-03-18 19:02

import cloudinary.models
import manage_tutorlinc.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0020_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[manage_tutorlinc.validators.validate_file_size], verbose_name='image'),
        ),
    ]
