# Generated by Django 5.0.6 on 2025-03-18 19:05

import manage_tutorlinc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0021_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/', validators=[manage_tutorlinc.validators.validate_file_size]),
        ),
    ]
