# Generated by Django 5.0.6 on 2025-03-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0023_teacher_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='id_verification',
            new_name='id_approved',
        ),
    ]
