# Generated by Django 5.0.6 on 2025-04-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0024_rename_id_verification_verification_id_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='addresses', serialize=False, to='manage_tutorlinc.teacher'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='manage_tutorlinc.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='manage_tutorlinc.teacher'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verifications', serialize=False, to='manage_tutorlinc.teacher'),
        ),
    ]
