# Generated by Django 5.0.6 on 2025-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0025_alter_address_teacher_alter_inquiry_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='day_to_teach',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
