# Generated by Django 5.0.6 on 2025-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0026_alter_subject_day_to_teach_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.FileField(upload_to='verification_certificates/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_card',
            field=models.FileField(upload_to='verification_certificates/'),
        ),
    ]
