# Generated by Django 5.0.6 on 2025-04-07 18:27

import django.core.validators
import manage_tutorlinc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0027_alter_verification_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_card',
            field=models.FileField(upload_to='verification_certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf']), manage_tutorlinc.validators.validate_file_size]),
        ),
    ]
