# Generated by Django 5.0.6 on 2025-04-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0028_alter_verification_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='certificate',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_card',
            field=models.URLField(),
        ),
    ]
