# Generated by Django 5.0.6 on 2025-04-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_tutorlinc', '0029_alter_verification_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.URLField(),
        ),
    ]
